name: paparazzi
dependencies:
- python=3.6
- pip
- pip:
  - beautifulsoup4
  - gensim
  - jupyter
  - keras
  - matplotlib
  - networkx
  - nltk
  - numpy
  - pandas
  - scikit-learn
  - requests
  - rouge
  - tensorflow

